### ISSUE TITLE
Loading package without prompts

### ISSUE THREAD

**Issue by angusrtaylor** [cloudyr/AzureStor#20]
I do not need to authenticate using AzureStor but I can't load the package without these prompts appearing. Is there a way to load the package without being prompted?

AzureAuth can cache Azure Active Directory tokens in the directory:

/home/anta/.local/share/AzureR

This saves you having to re-authenticate with Azure in future sessions. Create this directory? (Y/n) n
AzureRMR can cache Azure Resource Manager logins in the directory:

/home/anta/.local/share/AzureR

This saves you having to re-authenticate with Azure in future sessions. Create this directory? (Y/n)

**Comment by Hong-Revo** [comment]
There's a few things:

First, ideally AzureAuth (which is the source of the first message) would just create the directory silently, rather than bothering you about it. This is what every other cloud engineering tool does, eg Docker, Kubernetes, Az CLI, etc. The prompt is because of CRAN policy that any package that makes changes to the filesystem has to clear it with the user.

Second, AzureStor can authenticate with a token, so the caching is actually relevant. You give your app "Storage blob data contributor" access to the storage account, and then obtain a token with `"https://storage.azure.com"` as the resource.

I would recommend just letting AzureAuth create that directory, as otherwise you lose a fair chunk of usability. A bug is that you probably shouldn't get two prompts; I'll fix AzureRMR to not try to create the directory itself.

**Comment by angusrtaylor** [comment]
The problem is I want to use AzureStor inside a docker container (inside an Azure Batch job using doAzureParallel). I'm using AzureStor to read and write from blob using the storage account key to authenticate. With this prompt the script is going to hang I think. Is there a way round this?

**Comment by nickforr** [comment]
Hi, random thought, can’t test (sorry) but can you l call the package functions using the namespace rather than loading (using ‘::’)?

**Comment by Hong-Revo** [comment]
Per chat on Teams:

The prompt should only appear in an interactive environment, which won't be the case inside a batch job (hopefully). To be absolutely sure, you can create the caching directory beforehand:
```r
dir.create(rappdirs::user_data_dir(appname = "AzureR", appauthor = "", roaming = FALSE))
```
